server:
  port: 8088
  servlet:
    context-path: /studentjournal
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db_student_journal
    username: admin
    password: admin
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2